import { connectDB } from "./db.js";
const db = await connectDB();
import {client} from "./db.js"

try{
const command='collMod'
 await db.command({
  [command]: "users",
  validator: {
  $jsonSchema: {
    bsonType: 'object',
    title: 'User',
    description: 'User account document enforced at MongoDB level',
    required: [
      '_id',
      'name',
      'email',
      'password',
      'rootDirId',
      'storage',
      'state',
      'createdAt',
      'updatedAt',
      '__v'
    ],
    additionalProperties: false,
    properties: {
      _id: {
        bsonType: 'objectId',
        description: 'Primary identifier generated by MongoDB'
      },
      name: {
        bsonType: 'string',
        minLength: 4,
        description: 'User public username (minimum 4 characters)'
      },
      email: {
        bsonType: 'string',
        pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
        description: 'User email address'
      },
      password: {
        bsonType: 'string',
        minLength: 4,
        description: 'Hashed user password'
      },
      rootDirId: {
        bsonType: 'objectId',
        description: 'Root directory owned by the user'
      },
      storage: {
        bsonType: 'int',
        minimum: 0,
        description: 'Total storage used by the user in bytes'
      },
      state: {
        bsonType: 'string',
        'enum': [
          'ACTIVE',
          'DELETED',
          'DISABLED',
          'SUSPENDED'
        ],
        description: 'Lifecycle state of the user account'
      },
      deletedAt: {
        bsonType: [
          'date',
          'null'
        ],
        description: 'Document creation timestamp (Mongoose)'
      },
      createdAt: {
        bsonType: 'date',
        description: 'Document creation timestamp (Mongoose)'
      },
      updatedAt: {
        bsonType: 'date',
        description: 'Last update timestamp (Mongoose)'
      },
      __v: {
        bsonType: 'int',
        minimum: 0,
        description: 'Mongoose internal version key'
      }
    }
  }
}
,
  validationLevel:"strict",
validationAction:"error"
});
 await db.command({
  [command]: "files",
  validator: {
  $jsonSchema: {
    bsonType: 'object',
    title: 'File',
    description: 'File metadata document stored by Mongoose',
    required: [
      '_id',
      'name',
      'storageKey',
      'storagePath',
      'extension',
      'mimeType',
      'size',
      'parentDirId',
      'userId',
      'state',
      'createdAt',
      'updatedAt',
      '__v'
    ],
    additionalProperties: false,
    properties: {
      _id: {
        bsonType: 'objectId',
        description: 'Primary identifier generated by MongoDB'
      },
      name: {
        bsonType: 'string',
        minLength: 1,
        description: 'Logical file name shown to the user'
      },
      storageKey: {
        bsonType: 'string',
        description: 'Unique physical storage key or filename'
      },
      storagePath: {
        bsonType: 'string',
        description: 'Disk path or object storage bucket path'
      },
      extension: {
        bsonType: 'string',
        description: 'File extension in lowercase (e.g., pdf, jpg, mp4)'
      },
      mimeType: {
        bsonType: 'string',
        description: 'MIME type of the file (e.g., application/pdf)'
      },
      size: {
        bsonType: 'number',
        minimum: 0,
        description: 'File size in bytes'
      },
      parentDirId: {
        bsonType: 'objectId',
        description: 'Directory in which this file resides'
      },
      userId: {
        bsonType: 'objectId',
        description: 'Owner user ObjectId'
      },
      state: {
        bsonType: 'string',
        'enum': [
          'ACTIVE',
          'TRASHED',
          'DELETED'
        ],
        description: 'Lifecycle state of the file'
      },
      trashedAt: {
        bsonType: [
          'date',
          'null'
        ],
        description: 'Timestamp when file was moved to trash'
      },
      deletedAt: {
        bsonType: [
          'date',
          'null'
        ],
        description: 'Timestamp when file was permanently deleted'
      },
      createdAt: {
        bsonType: 'date',
        description: 'Document creation timestamp (Mongoose)'
      },
      updatedAt: {
        bsonType: 'date',
        description: 'Last update timestamp (Mongoose)'
      },
      __v: {
        bsonType: 'int',
        minimum: 0,
        description: 'Mongoose internal version key'
      }
    }
  }
}
,
validationLevel:"strict",
validationAction:"error"
});

await db.command({
  [command]: "dirs",
  validator: {
  $jsonSchema: {
    bsonType: 'object',
    title: 'Directory',
    description: 'Directory document stored by Mongoose',
    required: [
      '_id',
      'name',
      'userId',
      'state',
      'createdAt',
      'updatedAt',
      '__v'
    ],
    additionalProperties: false,
    properties: {
      _id: {
        bsonType: 'objectId',
        description: 'Primary identifier generated by MongoDB'
      },
      name: {
        bsonType: 'string',
        minLength: 1,
        description: 'Directory name'
      },
      parentDirId: {
        bsonType: [
          'objectId',
          'null'
        ],
        description: 'Parent directory ObjectId (null for root)'
      },
      userId: {
        bsonType: 'objectId',
        description: 'Owner user ObjectId'
      },
      state: {
        bsonType: 'string',
        'enum': [
          'ACTIVE',
          'TRASHED',
          'DELETED'
        ],
        description: 'Lifecycle state of the directory'
      },
      trashedAt: {
        bsonType: [
          'date',
          'null'
        ],
        description: 'Timestamp when directory was moved to trash'
      },
      deletedAt: {
        bsonType: [
          'date',
          'null'
        ],
        description: 'Timestamp when directory was permanently deleted'
      },
      createdAt: {
        bsonType: 'date',
        description: 'Document creation timestamp (Mongoose)'
      },
      updatedAt: {
        bsonType: 'date',
        description: 'Last update timestamp (Mongoose)'
      },
      __v: {
        bsonType: 'int',
        minimum: 0,
        description: 'Mongoose internal version key'
      }
    }
  }
}
,
validationLevel:"strict",
validationAction:"error"
});

}catch(error){
    console.log("Error While setting up Database",error)
}finally{
client.close();
}